### ISSUE TITLE
-logFile /dev/stdout not supported

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#11]
Looking at using /dev/stdout as a workaround for #3, it is currently not supported.

````
$ u3d --trace -r -- -logFile /dev/stdout -executeMethod U3d.EditorRun.Build -quit -batchmode 
/Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/lib/u3d/unity_runner.rb:34:in `delete': Permission denied @ unlink_internal - /dev/stdout (Errno::EACCES)
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/lib/u3d/unity_runner.rb:34:in `run'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/lib/u3d/commands.rb:207:in `run'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/lib/u3d/commands_generator.rb:79:in `block (2 levels) in run'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/lib/u3d/commands_generator.rb:160:in `run'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/lib/u3d/commands_generator.rb:36:in `start'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/gems/u3d-0.9.1/exe/u3d:7:in `<top (required)>'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/bin/u3d:23:in `load'
	from /Users/lacostej/.rvm/gems/ruby-2.1.1/bin/u3d:23:in `<main>'
````

**Comment by lacostej** [comment]
This is partially fixed. The pretifyer isn't plugged, but I'll open a new issue for that.
