### ISSUE TITLE
u3d: non UTF-8 environments can cause issues.

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#147]
If you hit

```
[07:43:23] Failure while trying to pipe /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/editor.log: invalid byte sequence in US-ASCII
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d_core/ui/implementations/shell.rb:111:in `split'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d_core/ui/implementations/shell.rb:111:in `command_output'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d_core/ui/ui.rb:38:in `method_missing'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:36:in `block in run'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:105:in `block (2 levels) in start_tail_thread'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:124:in `block (2 levels) in pipe'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/file-tail-1.2.0/lib/file/tail.rb:209:in `read_line'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/file-tail-1.2.0/lib/file/tail.rb:181:in `block in tail'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/file-tail-1.2.0/lib/file/tail.rb:178:in `loop'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/file-tail-1.2.0/lib/file/tail.rb:178:in `tail'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:124:in `block in pipe'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:118:in `open'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:118:in `pipe'
[07:43:23]   /Users/adminwwtk/jenkins/workspace/game_ChessProto-master_mac/.bundle/ruby/2.3.0/gems/u3d-1.0.3/lib/u3d/unity_runner.rb:105:in `block in start_tail_thread'
```

solution is
```
export LANG=en_US.UTF-8
```

Is there a way to prevent this? If not, can we help the user to fix his setup?

**Comment by marklonquist** [comment]
Adding export LANG=en_US.UTF-8 to .bash_profile and restarting machine did not help. I'm still getting; 
`Failure while trying to pipe /Users/byggefar/Library/Logs/Unity/Editor.log: invalid byte sequence in US-ASCII`

Anything else I can try? :-)
