### ISSUE TITLE
`install': uninitialized constant U3d::Globals (NameError)

### ISSUE THREAD

**Issue by marklonquist** [DragonBox/u3d#166]
I have an issue after updating the u3d gem:

```
[09:23:03]	[Step 1/5] /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.7/lib/u3d/commands.rb:130:in `install': uninitialized constant U3d::Globals (NameError)
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.7/lib/u3d/commands_generator.rb:147:in `block (2 levels) in run'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.7/lib/u3d/commands_generator.rb:195:in `run'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.7/lib/u3d/commands_generator.rb:37:in `start'
[09:23:03]	[Step 1/5] from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.7/exe/u3d:7:in `<main>'
```

Any solution to this :( ?

**Comment by niezbop** [comment]
I'm fixing it right away! I'll provide a hotfix in a few minutes

**Comment by marklonquist** [comment]
@niezbop copied your fix into the file - Worked :-)

**Comment by niezbop** [comment]
@marklonquist Great! Glad it did
