### ISSUE TITLE
package "VisualStudio" on 2018.1.0b2

### ISSUE THREAD

**Issue by m-ronchi** [DragonBox/u3d#225]
if i try
`u3d install 2018.1.0b2 -p VisualStudio`
it gives me this error:
```
/usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/downloader.rb:139:in `destination_for': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/downloader.rb:98:in `get_package'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/downloader.rb:52:in `block in download_modules'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/downloader.rb:51:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/downloader.rb:51:in `download_modules'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/downloader.rb:40:in `fetch_modules'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/commands.rb:131:in `install'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/commands_generator.rb:151:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/commands_generator.rb:209:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/lib/u3d/commands_generator.rb:37:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/u3d-1.0.12/exe/u3d:7:in `<top (required)>'
	from /usr/local/bin/u3d:23:in `load'
	from /usr/local/bin/u3d:23:in `<main>'
```

**Comment by niezbop** [comment]
Hey @m-ronchi ! I'll look into this asap!

**Comment by lacostej** [comment]
Interesting. The 2018 editor requires some EULA acceptance steps before we can download those components. I will have to discuss with @niezbop how to solve this.

**Comment by lacostej** [comment]
````
[VisualStudio]
title=Visual Studio for Mac
description=Script IDE with Unity integration and debugging support. Also installs Mono, required for Visual Studio for Mac to run
url=https://go.microsoft.com/fwlink/?linkid=857640
install=true
mandatory=false
size=820000000
installedsize=2304000000
eulamessage=Please review and accept the license terms before downloading and installing Visual Studio for Mac and Mono.
eulalabel1=Visual Studio for Mac License Terms
eulaurl1=https://www.visualstudio.com/license-terms/visual-studio-mac-eula/
eulalabel2=Mono License Terms
eulaurl2=http://www.mono-project.com/docs/faq/licensing/
appidentifier=com.microsoft.visual-studio
````

**Comment by niezbop** [comment]
I suppose you are running on Mac. Interstingly enough, it does not behave the same way on Windows:
```
---------------------------------------------------
--- Downloading VisualStudio version 2018.1.0b2 ---
---------------------------------------------------
Downloading from https://beta.unity3d.com/download/79c3bdce0980/https://aka.ms/vs/15/release/vs_Community.exe
Download will be found at C:/Users/pniez/Downloads/Unity_Packages/2018.1.0b2/vs_Community.exe
[===================>] 347.00 B/347.00 B (100.0% at 347.00 B/s)
File looks corrupted (wrong size)
Failed to download VisualStudio
```

But yeah @lacostej , we'll need to tackle how we handle EULA

**Comment by lacostej** [comment]
@niezbop the URL is still wrong on Windows it seems. And we will need to work on detecting if the tool is already present or not (because you don't want to install VS for every release), and if we can automate the installation, etc.

Some links:
https://social.msdn.microsoft.com/Forums/en-US/bd0567c4-da60-4102-8d90-c6006ff603a5/installing-vs-2017-rc-using-commandline-unattended-install?forum=vssetup

**Comment by lacostej** [comment]
#227 is a work in progress. I don't have windows so I won't be able to test all of it. Statuses updated in the PR

**Comment by lacostej** [comment]
Hello @m-ronchi, u3d 1.0.14 released today should support Unity 2018.1 beta downloads and installs. Tested on Mac / Windows.

**Comment by m-ronchi** [comment]
just tried (`u3d install latest_beta -a`)
it installed everything except Mono(?) and VS
```
-------------------------------------------
--- Downloading Mono version 2018.1.0b2 ---
-------------------------------------------
Downloading from https://download.visualstudio.microsoft.com/download/pr/100361130/02c722fa0388eacff31d7d9db909278e/MonoFramework-MDK-5.4.1.7.macos10.xamarin.universal.pkg
Download will be found at /Users/***/Downloads/Unity_Packages/2018.1.0b2/MonoFramework-MDK-5.4.1.7.macos10.xamarin.universal.pkg
[===================>] 470.81 MiB/470.81 MiB (100.0% at 4.36 MiB/s)      
File looks corrupted (wrong size)
Failed to download Mono
---------------------------------------------------
--- Downloading VisualStudio version 2018.1.0b2 ---
---------------------------------------------------
Downloading from https://download.visualstudio.microsoft.com/download/pr/100470888/ddea83afa478a2710e50a617b9cb5660/VisualStudioForMac-7.3.2.12.pkg
Download will be found at /Users/***/Downloads/Unity_Packages/2018.1.0b2/VisualStudioForMac-7.3.2.12.pkg
[===================>] 416.50 MiB/416.50 MiB (100.0% at 3.31 MiB/s)      
File looks corrupted (wrong size)
Failed to download VisualStudio
```

(btw I already manually installed VS)

**Comment by lacostej** [comment]
@m-ronchi oops. My bad. Making a quick fix. I won't detect that VisualStudio is already installed though. But it should fix the installation.

**Comment by lacostej** [comment]
@m-ronchi try 1.0.15

![image](https://user-images.githubusercontent.com/24282/34978525-c7f5a7ea-fa9e-11e7-997e-9aed5e06c40c.png)
