### ISSUE TITLE
Unable to use U3D to install latest beta 2018.1.0b[8|7]

### ISSUE THREAD

**Issue by camerongibbs85** [DragonBox/u3d#255]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

u3d available lists 2018.1.0b8 but I can't be downloaded and installed by the following command. Same goes for 2018.1.0b7. However, 2018.1.0b6 works as expected.
```
C:\Users\Omen>u3d install 2018.1.0b8 --trace
Traceback (most recent call last):
        16: from C:/tools/ruby25/bin/u3d:23:in `<main>'
        15: from C:/tools/ruby25/bin/u3d:23:in `load'
        14: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/exe/u3d:7:in `<top (required)>'
        13: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands_generator.rb:37:in `start'
        12: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands_generator.rb:209:in `run'
        11: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
        10: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/runner.rb:68:in `run!'
         9: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
         8: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
         7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
         6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands_generator.rb:156:in `block (2 levels) in run'
         5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands.rb:122:in `install'
         4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands.rb:231:in `verify_package_names'
         3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands.rb:231:in `each'
         2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d/commands.rb:232:in `block in verify_package_names'
         1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d_core/ui/ui.rb:38:in `method_missing'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/u3d-1.0.16/lib/u3d_core/ui/interface.rb:168:in `user_error!': package 'Unity' doesn't exist (U3dCore::Interface::UIError)
```

**Comment by lacostej** [comment]
Mmm we will look into this during the week!
