### ISSUE TITLE
incompatible character encodings: CP850 and UTF-8

### ISSUE THREAD

**Issue by KyleOrth** [DragonBox/u3d#268]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

When running using **u3d run -r ...** an error will come out when parsing one line of output from Unity:

`[17:33:24] [31mFailure while trying to pipe D:\Jenkins\workspace\Morphite_XboxOne/Unity3d_Editor.log: incompatible character encodings: CP850 and UTF-8[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d_core/ui/implementations/shell.rb:111:in `include?'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d_core/ui/implementations/shell.rb:111:in `block in command_output'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d_core/ui/implementations/shell.rb:110:in `each'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d_core/ui/implementations/shell.rb:110:in `command_output'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d_core/ui/ui.rb:38:in `method_missing'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:36:in `block in run'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:105:in `block (2 levels) in start_tail_thread'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:124:in `block (2 levels) in pipe'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/file-tail-1.2.0/lib/file/tail.rb:209:in `read_line'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/file-tail-1.2.0/lib/file/tail.rb:181:in `block in tail'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/file-tail-1.2.0/lib/file/tail.rb:178:in `loop'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/file-tail-1.2.0/lib/file/tail.rb:178:in `tail'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:124:in `block in pipe'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:118:in `open'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:118:in `pipe'[0m
[17:33:24] [31m  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.18/lib/u3d/unity_runner.rb:105:in `block in start_tail_thread'[0m`

The output from Unity is the following line (notice the quotes around LightingData are the Unicode left / right quotation marks):

`Lighting data asset ‘LightingData’ is incompatible with the current Unity version. Please use Generate Lighting to rebuild the lighting data.  Realtime Global Illumination cannot be used until the lighting data is rebuilt.`

This only gets logged out when using the -r / --raw_logs flag - otherwise it seems to ignore that log message and avoid the problem.

**Comment by lacostej** [comment]
@KyleOrth thanks for reporting the issue.

Have you tried setting these variables in your environment before running u3d?
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

I think we forgot to document that!
