### ISSUE TITLE
installation.rb:210:in ``': No such file or directory - strings (Errno::ENOENT)

### ISSUE THREAD

**Issue by arhcy** [DragonBox/u3d#326]
### Issue Checklist

- [*] I'm using the latest u3d version
- [*] I ran `u3d --help`
- [*] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [*] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

- running on Ubuntu Server 18.04.01 LTS
- installed u3d with `gem install u3d`
- got error after runnig several commands
- --trace option shows:
```
archy@ubuntu1:~$ u3d list --trace
Traceback (most recent call last):
        20: from /usr/local/bin/u3d:23:in `<main>'
        19: from /usr/local/bin/u3d:23:in `load'
        18: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/exe/u3d:7:in `<top (required)>'
        17: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/commands_generator.rb:40:in `start'
        16: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/commands_generator.rb:260:in `run'
        15: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/delegates.rb:15:in `run!'
        14: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:68:in `run!'
        13: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/runner.rb:446:in `run_active_command'
        12: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:153:in `run'
        11: from /var/lib/gems/2.5.0/gems/commander-4.4.6/lib/commander/command.rb:182:in `call'
        10: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/commands_generator.rb:109:in `block (2 levels) in run'
         9: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/commands.rb:53:in `list_installed'
         8: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/commands.rb:53:in `each'
         7: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/commands.rb:56:in `block in list_installed'
         6: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:243:in `build_number'
         5: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:199:in `find_build_number'
         4: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:199:in `each'
         3: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:200:in `block in find_build_number'
         2: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:223:in `find_build_number_in'
         1: from /var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:210:in `strings'
/var/lib/gems/2.5.0/gems/u3d-1.1.2/lib/u3d/installation.rb:210:in ``': No such file or directory - strings (Errno::ENOENT)

```

**Comment by lacostej** [comment]
Hello, we use the `strings` program to search for the program version. It appears it isn't installed on the machine you are. We will need to update the code to search for it or to have an alternative implementation. In the mean time please install the `binutils` package.

https://packages.ubuntu.com/bionic/binutils

**Comment by lacostej** [comment]
@arhcy  You might want to try #327 and see if that works without installing `bintuils`
