### ISSUE TITLE
`user_error!': package 'Mac' doesn't exist

### ISSUE THREAD

**Issue by nbelisle11** [DragonBox/u3d#340]
Attempting to run `u3d install 2018.3.0f2 -p Unity,Mac,Windows --verbose -t;` throws an error

> Step 3/4 : RUN export LC_ALL=en_US.UTF-8;   export LANG=en_US.UTF-8;   sudo u3d install 2018.3.0f2 -p Unity,Mac,Windows --verbose -t;
>  ---> Running in 6c113e9e48a0
> WARNING! Your Locale system appears to be incompatible with Unicode. Set you LOCALE appropriately
> See https://github.com/DragonBox/u3d#setup
> INFO Fetching central 'versions.json' cache
> DEBUG Using http opts: {:use_ssl=>#<MatchData "https">, :read_timeout=>300}
> DEBUG Searching for ini file at https://beta.unity3d.com/download/6e9a27477296/unity-2018.3.0f2-linux.ini
> DEBUG Found list_installed_paths: []
> DEBUG Found debian_installed_paths: []
> DEBUG Version 2018.3.0f2 of Unity is not installed yet
> /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d_core/ui/interface.rb:168:in `user_error!': package 'Mac' doesn't exist (U3dCore::Interface::UIError)
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d_core/ui/ui.rb:38:in `method_missing'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands.rb:278:in `block in verify_package_names'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands.rb:277:in `each'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands.rb:277:in `verify_package_names'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands.rb:162:in `install'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands_generator.rb:173:in `block (2 levels) in run'
> 	from /var/lib/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
> 	from /var/lib/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
> 	from /var/lib/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
> 	from /var/lib/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
> 	from /var/lib/gems/2.3.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands_generator.rb:260:in `run'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/lib/u3d/commands_generator.rb:40:in `start'
> 	from /var/lib/gems/2.3.0/gems/u3d-1.1.3/exe/u3d:7:in `<top (required)>'
> 	from /usr/local/bin/u3d:23:in `load'
> 	from /usr/local/bin/u3d:23:in `<main>'
> The command '/bin/sh -c export LC_ALL=en_US.UTF-8;   export LANG=en_US.UTF-8;   sudo u3d install 2018.3.0f2 -p Unity,Mac,Windows --verbose -t;' returned a non-zero code: 1

Running this on ubuntu:16.04 in attempt to create a docker image with the 2018.3.0f2 Unity for headless builds. Dockerfile here - https://gitlab.com/nbelisle11/unity3d/blob/master/Dockerfile

This command still works for 2017.4.8f1.

I've confirmed that `u3d available -p -o mac` returns

> Version 2018.3.0f2: https://download.unity3d.com/download_unity/6e9a27477296/
> Packages:
>  - Unity
>  - Mono
>  - VisualStudio
>  - Android
>  - iOS
>  - AppleTV
>  - Linux
>  - Mac-IL2CPP
>  - Vuforia-AR
>  - WebGL
>  - Windows-Mono
>  - Facebook-Games

**Comment by nbelisle11** [comment]
`u3d install 2018.3.0f2 -p Unity,Mac-IL2CPP --verbose -t;` fails with the same error

**Comment by nbelisle11** [comment]
Ugh I'm an idiot. I thought that `u3d available -p -o mac` was telling me which versions were available which contained the `mac` package. Not which versions and packages are available for installation on a `mac`.

`u3d install 2018.3.0f2 -p Unity,Mac-Mono,Windows-Mono --verbose -t;` solved my problem, thanks so much for the detailed response!
