### ISSUE TITLE
Cannot start u3d within a working directory which path contains special characters.

### ISSUE THREAD

**Issue by scassard** [DragonBox/u3d#352]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

I ran into an issue when trying to run u3d within a working directory which path contains special characters.

```
$ pwd
/c/Users/Sébastien/Documents/Dev/wwtk.loginaccess

Sébastien@LAPTOP-LML47M4J MINGW64 ~/Documents/Dev/wwtk.loginaccess (master)
$ u3d --trace
[12:36:05] Unable to retrieve the editor logfile: Local Appdata retrieved (C:/Users/S�bastien/AppData/Local) is not correct
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/unity_runner.rb:75:in `dirname': no implicit conversion of nil into String (TypeError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/unity_runner.rb:75:in `find_and_prepare_logfile'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/unity_runner.rb:32:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:214:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:99:in `block (2 levels) in run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:260:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:40:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/exe/u3d:7:in `<top (required)>'
        from C:/Ruby23-x64/bin/u3d:23:in `load'
        from C:/Ruby23-x64/bin/u3d:23:in `<main>'
```

**Comment by lacostej** [comment]
@scassard the relevant code is the following

```
  class WindowsInstallation < Installation
    def default_log_file
      if @logfile.nil?
        begin
          loc_appdata = Utils.windows_local_appdata
          log_dir = File.expand_path('Unity/Editor/', loc_appdata)
          UI.important "Log directory (#{log_dir}) does not exist" unless Dir.exist? log_dir
          @logfile = File.expand_path('Editor.log', log_dir)
        rescue RuntimeError => ex
          UI.error "Unable to retrieve the editor logfile: #{ex}"
        end
      end
      @logfile
    end

class Utils
      def self.windows_local_appdata
        require 'win32api'

        windir = ' ' * 261

        getdir = Win32API.new('shell32', 'SHGetFolderPath', 'LLLLP', 'L')
        result = getdir.call(0, CSIDL_LOCAL_APPDATA, 0, 0, windir)
        raise "Unable to get Local Appdata directory, returned with value #{result}" unless result.zero?
        windir.rstrip!
        windir = File.expand_path(windir.rstrip)

        return windir if Dir.exist? windir
        raise "Local Appdata retrieved (#{windir}) is not correct"
      end
end
```

this fails under `windows_local_appdata` somewhere.

could you try `u3d console` and experiment with the various calls to see what goes wrong? In particular I am interested in the value of `result` and `windir`.

**Comment by lacostej** [comment]
Or maybe we need to do something like https://github.com/FAForever/client/pull/513/files

**Comment by lacostej** [comment]
Or maybe the issue is related to Unicode. See https://github.com/pypa/pip/blob/master/src/pip/_internal/utils/appdirs.py#L219-L242

**Comment by lacostej** [comment]
Note that maybe we just need to call the unicode specific version of `SHGetFolderPath`, i.e. `SHGetFolderPathW`, or its replacement `SHGetKnownFolderPath`

**Comment by scassard** [comment]
> 
> 
> @scassard the relevant code is the following
> 
> ```
>   class WindowsInstallation < Installation
>     def default_log_file
>       if @logfile.nil?
>         begin
>           loc_appdata = Utils.windows_local_appdata
>           log_dir = File.expand_path('Unity/Editor/', loc_appdata)
>           UI.important "Log directory (#{log_dir}) does not exist" unless Dir.exist? log_dir
>           @logfile = File.expand_path('Editor.log', log_dir)
>         rescue RuntimeError => ex
>           UI.error "Unable to retrieve the editor logfile: #{ex}"
>         end
>       end
>       @logfile
>     end
> 
> class Utils
>       def self.windows_local_appdata
>         require 'win32api'
> 
>         windir = ' ' * 261
> 
>         getdir = Win32API.new('shell32', 'SHGetFolderPath', 'LLLLP', 'L')
>         result = getdir.call(0, CSIDL_LOCAL_APPDATA, 0, 0, windir)
>         raise "Unable to get Local Appdata directory, returned with value #{result}" unless result.zero?
>         windir.rstrip!
>         windir = File.expand_path(windir.rstrip)
> 
>         return windir if Dir.exist? windir
>         raise "Local Appdata retrieved (#{windir}) is not correct"
>       end
> end
> ```
> 
> this fails under `windows_local_appdata` somewhere.
> 
> could you try `u3d console` and experiment with the various calls to see what goes wrong? In particular I am interested in the value of `result` and `windir`.


=====

I tried to run the command `U3d::Utils.windows_local_appdata`, as expected I got an error :
```
>> U3d::Utils.windows_local_appdata
RuntimeError: Local Appdata retrieved (C:/Users/S�bastien/AppData/Local) is not correct
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/utils.rb:197:in `windows_local_appdata'
        from (irb):1:in `console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:82:in `block in console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:82:in `catch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:82:in `console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:236:in `block (2 levels) in run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:71:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:260:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:40:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/exe/u3d:7:in `<top (required)>'
        from C:/Ruby23-x64/bin/u3d:23:in `load'
        from C:/Ruby23-x64/bin/u3d:23:in `<main>'
```

Then I ran the instructions one by one to check where the error could be, here is what I got :
```
>> require 'win32api'
false
>> windir = ' ' * 261
"                                                                                                                                                                                                                                                                     "
>> getdir = Win32API.new('shell32', 'SHGetFolderPath', 'LLLLP', 'L')
#<Win32API:0x0000000529b620 @proto="IIIIS", @func=#<Fiddle::Function:0x0000000529ae00 @ptr=140707655506704, @args=[5, 5, 5, 5, 1], @return_type=5, @abi=1>>
>> CSIDL_LOCAL_APPDATA = 0x001c
28
>> result = getdir.call(0, CSIDL_LOCAL_APPDATA, 0, 0, windir)
0
>> windir
"C:\\Users\\S\xE9bastien\\AppData\\Local\u0000                                                                                                                                                                                                                                    "
>> windir.rstrip!
"C:\\Users\\S\xE9bastien\\AppData\\Local"
>> windir = File.expand_path(windir.rstrip)
"C:/Users/S\uFFFDbastien/AppData/Local"
>> Dir.exist? windir
false
>>
```

**Comment by lacostej** [comment]
@scassard could you try the following?

```
windir="C:\\Users\\S\xE9bastien\\AppData\\Local"
windir=windir.encode("UTF-8", "Windows-1252")
windir = File.expand_path(windir.rstrip)
Dir.exist? windir
```

**Comment by lacostej** [comment]
Also

```
puts  "ENV['RUBYOPT'] #{ENV['RUBYOPT']}" \
    "\nfilesystem     #{Encoding.find('filesystem')}" \
    "\nexternal       #{Encoding.default_external}" \
    "\n`chcp`         #{`chcp`}" \
      "locale         #{Encoding.find('locale')}" \
    "\n__ENCODING__   #{__ENCODING__}" \
    "\ninternal       #{Encoding.default_internal}"
```

**Comment by scassard** [comment]
> 
> 
> @scassard could you try the following?
> 
> ```
> windir="C:\\Users\\S\xE9bastien\\AppData\\Local"
> windir=windir.encode("UTF-8", "Windows-1252")
> windir = File.expand_path(windir.rstrip)
> Dir.exist? windir
> ```

```
>> windir="C:\\Users\\S\xE9bastien\\AppData\\Local"
"C:\\Users\\S\xE9bastien\\AppData\\Local"
>> windir=windir.encode("UTF-8", "Windows-1252")
"C:\\Users\\S\u00E9bastien\\AppData\\Local"
>> windir = File.expand_path(windir.rstrip)
"C:/Users/S\u00E9bastien/AppData/Local"
>> Dir.exist? windir
true
```
It seems to have solved the problem.

For the other instructions, I got this:
```
ENV['RUBYOPT']
filesystem     Windows-1252
external       CP850
locale         CP850
__ENCODING__   UTF-8
internal
nil
```

**Comment by lacostej** [comment]
@scassard one more thing we could try, what happens if you run u3d with a forced LOCALE as described in u3d's setup: https://github.com/DragonBox/u3d#setup
And then output both the  output of https://github.com/DragonBox/u3d/issues/352#issuecomment-475184108 and what you did in https://github.com/DragonBox/u3d/issues/352#issuecomment-474281224

**Comment by scassard** [comment]
I modified my `.bashrc` as specified in https://github.com/DragonBox/u3d#setup.

The `U3d::Utils.windows_local_appdata` command still gives the same message error : 
```
>> U3d::Utils.windows_local_appdata
RuntimeError: Local Appdata retrieved (C:/Users/S�bastien/AppData/Local) is not correct
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/utils.rb:197:in `windows_local_appdata'
        from (irb):1:in `console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:82:in `block in console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:82:in `catch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands.rb:82:in `console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:236:in `block (2 levels) in run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/runner.rb:71:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:260:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:40:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/u3d-1.1.5/exe/u3d:7:in `<top (required)>'
        from C:/Ruby23-x64/bin/u3d:23:in `load'
        from C:/Ruby23-x64/bin/u3d:23:in `<main>'
```
Then one by one instructions also gave the same outputs : 
```
false
>> windir = ' ' * 261
"                                                                                                                                                                                                                                                                     "
>> getdir = Win32API.new('shell32', 'SHGetFolderPath', 'LLLLP', 'L')
#<Win32API:0x0000000302cc38 @proto="IIIIS", @func=#<Fiddle::Function:0x00000002ffbd68 @ptr=140730539105040, @args=[5, 5, 5, 5, 1], @return_type=5, @abi=1>>
>>  CSIDL_LOCAL_APPDATA = 0x001c
28
>> result = getdir.call(0, CSIDL_LOCAL_APPDATA, 0, 0, windir)
0
>> windir
"C:\\Users\\S\xE9bastien\\AppData\\Local\u0000                                                                                                                                                                                                                                    "
>> windir.rstrip!
"C:\\Users\\S\xE9bastien\\AppData\\Local"
>> windir = File.expand_path(windir.rstrip)
"C:/Users/S\uFFFDbastien/AppData/Local"
>> Dir.exist? windir
false
```
For the other 2 instructions, they both seems to give the same results as before : 
```
>> windir="C:\\Users\\S\xE9bastien\\AppData\\Local"
"C:\\Users\\S\xE9bastien\\AppData\\Local"
>> windir=windir.encode("UTF-8", "Windows-1252")
"C:\\Users\\S\u00E9bastien\\AppData\\Local"
>> windir = File.expand_path(windir.rstrip)
"C:/Users/S\u00E9bastien/AppData/Local"
>> Dir.exist? windir
true
```
and 
```
?> puts  "ENV['RUBYOPT'] #{ENV['RUBYOPT']}" \
?>     "\nfilesystem     #{Encoding.find('filesystem')}" \
?>     "\nexternal       #{Encoding.default_external}" \
?>     "\nlocale         #{Encoding.find('locale')}" \
?>     "\n__ENCODING__   #{__ENCODING__}" \
?>     "\ninternal       #{Encoding.default_internal}"
ENV['RUBYOPT']
filesystem     Windows-1252
external       CP850
locale         CP850
__ENCODING__   UTF-8
internal
nil
```
