### ISSUE TITLE
2019.2.13f1 fails to install on linux

### ISSUE THREAD

**Issue by BastianBlokland** [DragonBox/u3d#391]
### Issue Checklist

- [ x] I'm using the latest u3d version
- [ x] I ran `u3d --help`
- [ x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [ x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

Thanks for the great tool, its been working great for the past year for us.
However `Unity 2019.2.13f1` fails to install on linux ci. Are there any workarounds available?

Logs:
```
[33mRoot privileges are required[0m
[32m---------------------------------------------------------[0m
[32m--- Downloading Unity 2019.2.13f1 version 2019.2.13f1 ---[0m
[32m---------------------------------------------------------[0m
Downloading from [4m[36mhttps://download.unity3d.com/download_unity/e20f6c7e5017/LinuxEditorInstaller/Unity.tar.xz[0m[0m
Download will be found at /home/vsts/Downloads/Unity_Packages/2019.2.13f1/Unity.tar.xz
[32mSuccessfully downloaded Unity.[0m
[32m--------------------------------------------[0m
[32m--- Installing Unity 2019.2.13f1 (Unity) ---[0m
[32m--------------------------------------------[0m
Installing with /home/vsts/Downloads/Unity_Packages/2019.2.13f1/Unity.tar.xz
[4m[36m$ mkdir -p /opt/unity-editor-2019.2.13f1; cd /opt/unity-editor-2019.2.13f1; tar xf /home/vsts/Downloads/Unity_Packages/2019.2.13f1/Unity.tar.xz[0m[0m
[32mInstallation successful[0m
/var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installation.rb:242:in `version': Couldn't find a module under /opt/unity-editor-2019.2.13f1/Editor/Data/ (RuntimeError)
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installer.rb:318:in `block in install'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installer.rb:318:in `select'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installer.rb:318:in `install'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installer.rb:61:in `block in install_modules'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installer.rb:58:in `each'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/installer.rb:58:in `install_modules'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/commands.rb:170:in `install'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/commands_generator.rb:173:in `block (2 levels) in run'
	from /var/lib/gems/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
	from /var/lib/gems/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
	from /var/lib/gems/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
	from /var/lib/gems/2.5.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/commands_generator.rb:260:in `run'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/lib/u3d/commands_generator.rb:40:in `start'
	from /var/lib/gems/2.5.0/gems/u3d-1.2.1/exe/u3d:7:in `<top (required)>'
	from /usr/local/bin/u3d:23:in `load'
	from /usr/local/bin/u3d:23:in `<main>'
```

**Comment by lacostej** [comment]
Most probably related to #384. I hope to have something working this week.
