### ISSUE TITLE
u3d available 403 and patch releases

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#402]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

When you run the command it returns a 403 when fetching patch releases, I don't know if Unity has changed anything on its side regarding "patch releases".

```mac-build01:~ jenkins$ u3d available --trace
Fetching central 'versions.json' cache
Cache is out of date. Updating cache for Mac OSX
Loading Unity lts releases
Found 71 lts releases.
Loading Unity stable releases
Found 232 stable releases.
Loading Unity patch releases
Traceback (most recent call last):
        26: from /Users/jenkins/.gems/bin/u3d:23:in `<main>'
        25: from /Users/jenkins/.gems/bin/u3d:23:in `load'
        24: from /Users/jenkins/.gems/gems/u3d-1.2.3/exe/u3d:7:in `<top (required)>'
        23: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/commands_generator.rb:41:in `start'
        22: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/commands_generator.rb:263:in `run'
        21: from /Users/jenkins/.gems/gems/commander-4.5.0/lib/commander/delegates.rb:15:in `run!'
        20: from /Users/jenkins/.gems/gems/commander-4.5.0/lib/commander/runner.rb:68:in `run!'
        19: from /Users/jenkins/.gems/gems/commander-4.5.0/lib/commander/runner.rb:446:in `run_active_command'
        18: from /Users/jenkins/.gems/gems/commander-4.5.0/lib/commander/command.rb:153:in `run'
        17: from /Users/jenkins/.gems/gems/commander-4.5.0/lib/commander/command.rb:182:in `call'
        16: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/commands_generator.rb:140:in `block (2 levels) in run'
        15: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/commands.rb:112:in `list_available'
        14: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/commands.rb:270:in `cache_versions'
        13: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/commands.rb:270:in `new'
        12: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/cache.rb:68:in `initialize'
        11: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/cache.rb:111:in `overwrite_cache'
        10: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/cache.rb:136:in `update_cache'
         9: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:146:in `list_available'
         8: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:308:in `list_available'
         7: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:295:in `fetch_all_channels'
         6: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:268:in `fetch_some'
         5: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:268:in `each'
         4: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:269:in `block in fetch_some'
         3: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/unity_versions.rb:163:in `fetch_version_paged'
         2: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/utils.rb:45:in `get_ssl'
         1: from /Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/utils.rb:49:in `page_content'
/Users/jenkins/.gems/gems/u3d-1.2.3/lib/u3d/utils.rb:79:in `follow_redirects': Request failed with status 403 (RuntimeError)
```

**Comment by BastianBlokland** [comment]
The same thing started happening for us today.

**Comment by brennenawana** [comment]
https://github.com/DragonBox/u3d/blob/master/lib/u3d/unity_versions.rb#L112
`UNITY_PATCHES = 'https://unity3d.com/unity/qa/patch-releases'.freeze`
This url is returning 403

**Comment by niezbop** [comment]
I checked this morning using `u3d available --no-central --force`, and got 403 as well. While this was purely a Unity change that caused the issue (and solved it), this highlights two other issues in u3d:
- will the **patches come back** to this page, or will we have to change the way we fetch those?
- such errors should not be blocking and prevent us from getting other releases and we should definitely consider **rescuing this type of situation** to limit their impact. A drawback to this would be that issues could be "hidden" for longer and harder to track when they eventually pop. I'm interested in your opinion on this issue, and the way you think we should handle those.

I'll monitor the first point in the coming days to analyze whether we lost the patch listing or not.

**Comment by brennenawana** [comment]
Response from Unity support

> Hi Brennen,
> 
> Thanks for your response,
> 
> spoken internally with our team in charge removing the QA patches site was a decision taken recently. 
> 
> The QA patches releases are not longer a thing. This is as we are getting more regular releases on the Unity editor and are properly tested so the need for patches have reduced and we have not had any patch release since 2018.  
> 
> However, if you have issues with the editor, please do let us know and we will do our best to help :)
> Best regards,
> Link
> Customer Service Analyst

**Comment by bdovaz** [comment]
What I don't understand is why they don't leave it like it is.

If you have an old project in a version of this you can't download it anymore 

What if they also take out all the 5.x's or 2017.x's...
