### ISSUE TITLE
u3d install gives error about missing Win32 dependency. 

### ISSUE THREAD

**Issue by curtisshipley** [DragonBox/u3d#415]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

I installed ruby via windows installer. Installed u3d via gem. Running u3d command to install unity gives an requirements error about Win32API.
```
> u3d install 2019.1.12f1 -p Unity,Android
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- Win32API (LoadError)
Did you mean?  win32/sspi
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/installation.rb:354:in `string_file_info'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/installation.rb:350:in `unity_version_info'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/installation.rb:330:in `version'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/installation.rb:393:in `version'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands.rb:340:in `block in check_unity_presence'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands.rb:340:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands.rb:340:in `find'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands.rb:340:in `check_unity_presence'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands.rb:154:in `install'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands_generator.rb:176:in `block (2 levels) in run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:61:in `run!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands_generator.rb:263:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/lib/u3d/commands_generator.rb:41:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/u3d-1.2.3/exe/u3d:7:in `<top (required)>'
        from C:/Ruby30-x64/bin/u3d:23:in `load'
        from C:/Ruby30-x64/bin/u3d:23:in `<main>'
```

**Comment by curtisshipley** [comment]
It looks to be an issue related to use the ruby windows installer. Using choco to install works, but then I encounter the crash mentioned in the other issue. Closing.
