### ISSUE TITLE
`u3d install 2019.4.35f1` fails at 1.3.0

### ISSUE THREAD

**Issue by KKrasnov** [DragonBox/u3d#421]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

Since 1.3.0 update `u3d install 2019.4.35f1` fails to execute with following error trace:

```
Traceback (most recent call last):
	17: from /usr/local/bin/u3d:23:in `<main>'
	16: from /usr/local/bin/u3d:23:in `load'
	15: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/exe/u3d:9:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/commands_generator.rb:43:in `start'
	13: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/commands_generator.rb:265:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 7: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/commands_generator.rb:178:in `block (2 levels) in run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/commands.rb:155:in `install'
	 5: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/commands.rb:155:in `new'
	 4: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/unity_version_definition.rb:43:in `initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/unity_module.rb:70:in `load_modules'
	 2: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/unity_module.rb:104:in `load_version_modules'
	 1: from /Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/hub_modules_parser.rb:39:in `load_modules'
/Library/Ruby/Gems/2.6.0/gems/u3d-1.3.0/lib/u3d/hub_modules_parser.rb:39:in `size': No such file or directory @ rb_file_s_size - /Users/admin/Library/Application Support/u3d/unity_hub_modules/2019.4.35f1-mac-modules.json (Errno::ENOENT)
```

I've checked `unity_hub_modules` folder. It contains all other version files but there is no particular `2019.4.35f1-mac-modules.json`
I'm lame at Ruby so it isn't clear to me why this particular might be missing. I assume this is the unknown consequence of https://github.com/DragonBox/u3d/pull/416

Would appreciate any help on this. Thanks in advance!

**Comment by lacostej** [comment]
Fix coming, sorry for that. The ruby style auto-correct code [introduced a bug](https://github.com/rubocop/rubocop/issues/10646).
