### ISSUE TITLE
Unable to install unity 2021.3.7f1 on windows

### ISSUE THREAD

**Issue by benholtz** [DragonBox/u3d#430]
### Issue Checklist

- [X] I'm using the latest u3d version
- [X] I ran `u3d --help`
- [X] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [X] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

```
C:\WINDOWS\system32>ruby --version
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]

C:\WINDOWS\system32>u3d install 2021.3.7f1 --trace --verbose
DEBUG Loading modules for version 2021.3.7f1
DEBUG Using http opts: {:use_ssl=>#<MatchData "https">, :read_timeout=>300}
DEBUG No modules registered for UnityHub for version 2021.3.7f1
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d_core/ui/interface.rb:171:in `user_error!': Unknown method 'info', supported [:success, :message, :password, :verbose, :interactive?, :crash!, :select, :error, :header, :important, :confirm, :deprecated, :command, :user_error!, :not_implemented, :command_output, :input] (U3dCore::Interface::UIError)
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d_core/ui/ui.rb:42:in `method_missing'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d_core/ui/ui.rb:40:in `method_missing'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/hub_modules_parser.rb:57:in `load_modules'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/unity_module.rb:104:in `load_version_modules'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/unity_module.rb:70:in `load_modules'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/unity_version_definition.rb:43:in `initialize'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/commands.rb:155:in `new'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/commands.rb:155:in `install'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/commands_generator.rb:178:in `block (2 levels) in run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/commands_generator.rb:265:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/lib/u3d/commands_generator.rb:43:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/u3d-1.3.2/exe/u3d:9:in `<top (required)>'
        from C:/tools/ruby31/bin/u3d:32:in `load'
        from C:/tools/ruby31/bin/u3d:32:in `<main>'
        
C:\WINDOWS\system32>u3d --version
u3d 1.3.2

```
<img width="537" alt="image" src="https://user-images.githubusercontent.com/231303/182743267-2e70aba8-d72d-4968-b6a2-b51e44483209.png">

Ran the same install command  with an older unity version a few weeks ago on the same system. with no issues..

**Comment by delphinius81** [comment]
I'm having the same issue. Only 2021.3.6f1 will install. All the other 2021.3 LTS versions give the unknown command "info" error.
