### ISSUE TITLE
(linux) Too many redirections

### ISSUE THREAD

**Issue by chazix** [DragonBox/u3d#438]
### Issue Checklist

- [x ] I'm using the latest u3d version
- [ x] I ran `u3d --help`
- [ x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [ x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

- platform: ubuntu 18.04 lts
- running: `u3d available --trace` or `u3d available --no-central --trace` resolves in `Too many redirections`
```
u3d available --no-central --trace
Cache is out of date. Updating cache for Linux
Loading Unity releases
Traceback (most recent call last):
        33: from /usr/local/bin/u3d:23:in `<main>'
        32: from /usr/local/bin/u3d:23:in `load'
        31: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/exe/u3d:9:in `<top (required)>'
        30: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/commands_generator.rb:43:in `start'
        29: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/commands_generator.rb:265:in `run'
        28: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
        27: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/runner.rb:68:in `run!'
        26: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
        25: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
        24: from /var/lib/gems/2.5.0/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
        23: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/commands_generator.rb:142:in `block (2 levels) in run'
        22: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/commands.rb:113:in `list_available'
        21: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/commands.rb:275:in `cache_versions'
        20: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/commands.rb:275:in `new'
        19: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/cache.rb:72:in `initialize'
        18: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/cache.rb:115:in `overwrite_cache'
        17: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/cache.rb:140:in `update_cache'
        16: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:149:in `list_available'
        15: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:207:in `list_available'
        14: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:207:in `map'
        13: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:208:in `block in list_available'
        12: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:44:in `page_content'
        11: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:54:in `page_content'
        10: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         9: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         8: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         7: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         6: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         5: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         4: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         3: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         2: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
         1: from /var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
/var/lib/gems/2.5.0/gems/u3d-1.3.3/lib/u3d/utils.rb:60:in `follow_redirects': Too many redirections (RuntimeError)
```

I encountered this in the past, and was able to do a work around by bypassing the `UNITY_LINUX_DOWNLOADS` forums, as it is attempting to require the user to login: https://github.com/Animal-Team/u3d/commit/2de960ed7f1e19aedc610a86c62878b5b96a17c7

**Comment by the-iron-ryan** [comment]
I'm having this exact same issue running on Ubuntu 23.10

```
itas-admin@ubuntu-server:~/Unity_Projects/drift$ u3d available --no-central --trace
Cache is out of date. Updating cache for Linux
Loading Unity releases
/var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:60:in `follow_redirects': Too many redirections (RuntimeError)
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:87:in `follow_redirects'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/utils.rb:54:in `page_content'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:44:in `page_content'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:208:in `block in list_available'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:207:in `map'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:207:in `list_available'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/unity_versions.rb:149:in `list_available'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/cache.rb:140:in `update_cache'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/cache.rb:115:in `overwrite_cache'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/cache.rb:72:in `initialize'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/commands.rb:275:in `new'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/commands.rb:275:in `cache_versions'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/commands.rb:113:in `list_available'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/commands_generator.rb:142:in `block (2 levels) in run'
        from /var/lib/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /var/lib/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /var/lib/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
        from /var/lib/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/commands_generator.rb:265:in `run'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/lib/u3d/commands_generator.rb:43:in `start'
        from /var/lib/gems/3.1.0/gems/u3d-1.3.3/exe/u3d:9:in `<top (required)>'
        from /usr/local/bin/u3d:25:in `load'
        from /usr/local/bin/u3d:25:in `<main>'
```
Any updates on this?

**Comment by jrowinski3d** [comment]
Facing thee same issue here
