### ISSUE TITLE
u3d local_install broken on Mac

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#62]
````
$ u3d local_install latest --trace
Root privileges are required
Password for lacostej:
*******
No credentials storage available
/Users/lacostej/Code/WWTK/u3d/lib/u3d/downloader.rb:99:in `block in local_files': private method `local_file' called for U3d::Downloader::MacDownloader:Class (NoMethodError)
Did you mean?  local_variables
	from /Users/lacostej/Code/WWTK/u3d/lib/u3d/downloader.rb:98:in `each'
	from /Users/lacostej/Code/WWTK/u3d/lib/u3d/downloader.rb:98:in `local_files'
	from /Users/lacostej/Code/WWTK/u3d/lib/u3d/commands.rb:143:in `local_install'
	from /Users/lacostej/Code/WWTK/u3d/lib/u3d/commands_generator.rb:139:in `block (2 levels) in run'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/lacostej/Code/WWTK/u3d/lib/u3d/commands_generator.rb:161:in `run'
	from /Users/lacostej/Code/WWTK/u3d/lib/u3d/commands_generator.rb:37:in `start'
	from /Users/lacostej/Code/WWTK/u3d/exe/u3d:7:in `<top (required)>'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/bin/u3d:22:in `load'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/bin/u3d:22:in `<main>'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/lacostej/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
````

**Comment by lacostej** [comment]
Fixed by #63
