### ISSUE TITLE
List doesn't list all installed Unity versions

### ISSUE THREAD

**Issue by exlee** [DragonBox/u3d#69]
Result (I have 3 other Unity versions installed):

```xlii$ u3d list
Version 5.3.6f1                (/Applications/Unity_5.3.6f1/Unity.app)
error: Unity installation does not seem correct. Couldn't locate PlaybackEngines.. Use --trace to view backtrace
```

Directory listing:

```xlii$ ls -adl /Applications/Unity*
drwxrwxr-x  7 root  admin  238 21 mar  2016 /Applications/Unity.bak
drwxrwxr-x  5 root  admin  170 19 lip 14:52 /Applications/Unity_2017.1.0f3
drwxrwxr-x  5 root  admin  170 18 sie 11:27 /Applications/Unity_5.3.6f1
drwxrwxr-x  9 root  admin  306 26 kwi 16:35 /Applications/Unity_5.6.0f3
drwxrwxr-x  5 root  admin  170 10 sie 13:09 /Applications/Unity_5.6.3f1
```

*Note: Unity.bak doesn't affect the outcome. Removing it still doesn't resolve the issue*

Trace:
```
/Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/installer.rb:76:in `packages': Unity installation does not seem correct. Couldn't locate PlaybackEngines. (RuntimeError)
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/commands.rb:53:in `block in list_installed'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/commands.rb:50:in `each'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/commands.rb:50:in `list_installed'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/commands_generator.rb:89:in `block (2 levels) in run'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/commands_generator.rb:160:in `run'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/lib/u3d/commands_generator.rb:36:in `start'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/gems/u3d-0.9.3/exe/u3d:7:in `<top (required)>'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/bin/u3d:22:in `load'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/bin/u3d:22:in `<main>'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xlii/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lacostej** [comment]
@exlee is this because one of your installs has no packages?

**Comment by exlee** [comment]
It might be possible, as I installed without -p flag. How can I verify that?
